[pytest]
asyncio_mode = auto
testpaths = ../../tests/unit/management ../../tests/integration
addopts =
    -v
    --cov=app
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=90
    -p no:warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
