apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - management/deployment.yaml
  - management/service.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: waddleai
