{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penguincode.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "penguincode.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  {{- end }}
  {{- if .Values.secrets.PENGUINCODE_API_KEY }}
  PENGUINCODE_API_KEY: {{ .Values.secrets.PENGUINCODE_API_KEY }}
  {{- end }}
{{- end }}
