# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import knowledge_pb2 as knowledge_dot_v1_dot_knowledge__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in knowledge/v1/knowledge_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class KnowledgeServiceStub:
    """==================== KnowledgeService ===================="""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/Index",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.IndexRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.IndexResponse.FromString,
            _registered_method=True,
        )
        self.Query = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/Query",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.QueryRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.QueryResponse.FromString,
            _registered_method=True,
        )
        self.MemoryAdd = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/MemoryAdd",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.MemoryAddRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.MemoryAddResponse.FromString,
            _registered_method=True,
        )
        self.MemorySearch = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/MemorySearch",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.MemorySearchRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.MemorySearchResponse.FromString,
            _registered_method=True,
        )
        self.IndexCode = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/IndexCode",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.IndexCodeRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.IndexCodeResponse.FromString,
            _registered_method=True,
        )
        self.CodeGraphStatus = channel.unary_unary(
            "/penguincode.knowledge.v1.KnowledgeService/CodeGraphStatus",
            request_serializer=knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusRequest.SerializeToString,
            response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusResponse.FromString,
            _registered_method=True,
        )


class KnowledgeServiceServicer:
    """==================== KnowledgeService ===================="""

    def Index(self, request, context):
        """Index documentation for a library or a language's core docs. Mirrors
        `docs_rag.indexer.DocumentationIndexer.index_library` /
        `.index_language` -- the server embeds + upserts into `docs_vectors`
        and best-effort extracts a knowledge-graph enrichment alongside the
        vector write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Query(self, request, context):
        """Hybrid GraphRAG retrieval: scoped vector top-k + flag-gated graph
        expansion, assembled into one bounded context string. Mirrors
        `retrieval.graphrag.retrieve` / its `RetrievalResult`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MemoryAdd(self, request, context):
        """Write one scope-stamped memory. Mirrors
        `tools.memory.ScopedMemoryManager.add`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MemorySearch(self, request, context):
        """Search memories within the caller's scope. Mirrors
        `tools.memory.ScopedMemoryManager.search`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IndexCode(self, request, context):
        """(Re)build the code graph for a source tree. Mirrors
        `graphs.code.index_code`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CodeGraphStatus(self, request, context):
        """Report the caller-scoped code graph's current availability/size."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Index": grpc.unary_unary_rpc_method_handler(
            servicer.Index,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.IndexRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.IndexResponse.SerializeToString,
        ),
        "Query": grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.QueryRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.QueryResponse.SerializeToString,
        ),
        "MemoryAdd": grpc.unary_unary_rpc_method_handler(
            servicer.MemoryAdd,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.MemoryAddRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.MemoryAddResponse.SerializeToString,
        ),
        "MemorySearch": grpc.unary_unary_rpc_method_handler(
            servicer.MemorySearch,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.MemorySearchRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.MemorySearchResponse.SerializeToString,
        ),
        "IndexCode": grpc.unary_unary_rpc_method_handler(
            servicer.IndexCode,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.IndexCodeRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.IndexCodeResponse.SerializeToString,
        ),
        "CodeGraphStatus": grpc.unary_unary_rpc_method_handler(
            servicer.CodeGraphStatus,
            request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusRequest.FromString,
            response_serializer=knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "penguincode.knowledge.v1.KnowledgeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "penguincode.knowledge.v1.KnowledgeService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class KnowledgeService:
    """==================== KnowledgeService ===================="""

    @staticmethod
    def Index(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/Index",
            knowledge_dot_v1_dot_knowledge__pb2.IndexRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/Query",
            knowledge_dot_v1_dot_knowledge__pb2.QueryRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MemoryAdd(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/MemoryAdd",
            knowledge_dot_v1_dot_knowledge__pb2.MemoryAddRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.MemoryAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MemorySearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/MemorySearch",
            knowledge_dot_v1_dot_knowledge__pb2.MemorySearchRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.MemorySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IndexCode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/IndexCode",
            knowledge_dot_v1_dot_knowledge__pb2.IndexCodeRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.IndexCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CodeGraphStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.knowledge.v1.KnowledgeService/CodeGraphStatus",
            knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.CodeGraphStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
