# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import lessons_pb2 as lessons_dot_v1_dot_lessons__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in lessons/v1/lessons_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LessonsServiceStub:
    """==================== LessonsService ===================="""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PromoteLesson = channel.unary_unary(
            "/penguincode.lessons.v1.LessonsService/PromoteLesson",
            request_serializer=lessons_dot_v1_dot_lessons__pb2.PromoteLessonRequest.SerializeToString,
            response_deserializer=lessons_dot_v1_dot_lessons__pb2.PromoteLessonResponse.FromString,
            _registered_method=True,
        )
        self.ListPendingLessons = channel.unary_unary(
            "/penguincode.lessons.v1.LessonsService/ListPendingLessons",
            request_serializer=lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsRequest.SerializeToString,
            response_deserializer=lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsResponse.FromString,
            _registered_method=True,
        )
        self.ApproveLesson = channel.unary_unary(
            "/penguincode.lessons.v1.LessonsService/ApproveLesson",
            request_serializer=lessons_dot_v1_dot_lessons__pb2.ApproveLessonRequest.SerializeToString,
            response_deserializer=lessons_dot_v1_dot_lessons__pb2.ApproveLessonResponse.FromString,
            _registered_method=True,
        )
        self.RejectLesson = channel.unary_unary(
            "/penguincode.lessons.v1.LessonsService/RejectLesson",
            request_serializer=lessons_dot_v1_dot_lessons__pb2.RejectLessonRequest.SerializeToString,
            response_deserializer=lessons_dot_v1_dot_lessons__pb2.RejectLessonResponse.FromString,
            _registered_method=True,
        )


class LessonsServiceServicer:
    """==================== LessonsService ===================="""

    def PromoteLesson(self, request, context):
        """Propose a team-visibility lesson for firm-wide (tenant) sharing. Runs
        T-L1's scrub + verify pipeline server-side; a CLEAN result is
        persisted as a new PENDING lesson (`pending_id` returned), a non-clean
        result is rejected outright (`blocked=true` + the verifier's
        `findings`) and nothing is persisted -- see `PromoteLessonResponse`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPendingLessons(self, request, context):
        """List pending lessons in the caller's tenant (never team-scoped --
        review is a firm-wide administrative action). Defaults to
        `status = "pending"` when the request leaves `status` empty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApproveLesson(self, request, context):
        """Approve a pending lesson: the only path to firm-wide (tenant)
        visibility. T-L2b's handler is the sole caller responsible for then
        actually writing the lesson tenant-wide (e.g. into `memory_vectors`);
        this RPC's own effect is limited to the `pending_lessons` row's status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RejectLesson(self, request, context):
        """Reject a pending lesson with a human-readable reason. Never promoted;
        the row stays in `pending_lessons` for audit history (status
        "rejected"), it is not deleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LessonsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PromoteLesson": grpc.unary_unary_rpc_method_handler(
            servicer.PromoteLesson,
            request_deserializer=lessons_dot_v1_dot_lessons__pb2.PromoteLessonRequest.FromString,
            response_serializer=lessons_dot_v1_dot_lessons__pb2.PromoteLessonResponse.SerializeToString,
        ),
        "ListPendingLessons": grpc.unary_unary_rpc_method_handler(
            servicer.ListPendingLessons,
            request_deserializer=lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsRequest.FromString,
            response_serializer=lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsResponse.SerializeToString,
        ),
        "ApproveLesson": grpc.unary_unary_rpc_method_handler(
            servicer.ApproveLesson,
            request_deserializer=lessons_dot_v1_dot_lessons__pb2.ApproveLessonRequest.FromString,
            response_serializer=lessons_dot_v1_dot_lessons__pb2.ApproveLessonResponse.SerializeToString,
        ),
        "RejectLesson": grpc.unary_unary_rpc_method_handler(
            servicer.RejectLesson,
            request_deserializer=lessons_dot_v1_dot_lessons__pb2.RejectLessonRequest.FromString,
            response_serializer=lessons_dot_v1_dot_lessons__pb2.RejectLessonResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "penguincode.lessons.v1.LessonsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "penguincode.lessons.v1.LessonsService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class LessonsService:
    """==================== LessonsService ===================="""

    @staticmethod
    def PromoteLesson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.lessons.v1.LessonsService/PromoteLesson",
            lessons_dot_v1_dot_lessons__pb2.PromoteLessonRequest.SerializeToString,
            lessons_dot_v1_dot_lessons__pb2.PromoteLessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPendingLessons(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.lessons.v1.LessonsService/ListPendingLessons",
            lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsRequest.SerializeToString,
            lessons_dot_v1_dot_lessons__pb2.ListPendingLessonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ApproveLesson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.lessons.v1.LessonsService/ApproveLesson",
            lessons_dot_v1_dot_lessons__pb2.ApproveLessonRequest.SerializeToString,
            lessons_dot_v1_dot_lessons__pb2.ApproveLessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RejectLesson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/penguincode.lessons.v1.LessonsService/RejectLesson",
            lessons_dot_v1_dot_lessons__pb2.RejectLessonRequest.SerializeToString,
            lessons_dot_v1_dot_lessons__pb2.RejectLessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
