---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waddleai

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml

configMapGenerator:
  - name: waddleai-config
    behavior: merge
    literals:
      - FLASK_ENV=production
      - FLASK_DEBUG=false

secretGenerator:
  - name: waddleai-secrets
    behavior: merge
    literals:
      - RELEASE_MODE=false

images:
  - name: ghcr.io/penguintechinc/waddleai/management
    newTag: beta-latest
