---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waddleai

resources:
  - ../../base

patches:
  - path: replica-patch.yaml

images:
  - name: registry-dal2.penguintech.io/waddleai/management
    newTag: beta-latest
  - name: registry-dal2.penguintech.io/waddleai/webui
    newTag: beta-latest
