---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waddleai-mgmt
  namespace: waddleai
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waddleai-webui
  namespace: waddleai
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: waddleai
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: waddleai
spec:
  replicas: 1
