apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: waddleai-alpha
namePrefix: alpha-
commonLabels:
  environment: alpha
resources:
  - ../../base
replicas:
  - name: management
    count: 1
images:
  - name: registry-dal2.penguintech.io/waddleai/management
    newTag: latest
configMapGenerator:
  - name: waddleai-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - RELEASE_MODE=false
