# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import media_pb2 as marchproxy_dot_media__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marchproxy/media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaServiceStub(object):
    """MediaService provides RTMP/Media module specific operations.
    This extends the base ModuleService with media-specific functionality.
    Hardware and Capability Management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/marchproxy.MediaService/GetCapabilities',
                request_serializer=marchproxy_dot_media__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetEffectiveLimits = channel.unary_unary(
                '/marchproxy.MediaService/GetEffectiveLimits',
                request_serializer=marchproxy_dot_media__pb2.GetEffectiveLimitsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetEffectiveLimitsResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/marchproxy.MediaService/UpdatePolicy',
                request_serializer=marchproxy_dot_media__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/marchproxy.MediaService/GetPolicy',
                request_serializer=marchproxy_dot_media__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetPolicyResponse.FromString,
                _registered_method=True)
        self.ListStreams = channel.unary_unary(
                '/marchproxy.MediaService/ListStreams',
                request_serializer=marchproxy_dot_media__pb2.ListStreamsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.ListStreamsResponse.FromString,
                _registered_method=True)
        self.GetStream = channel.unary_unary(
                '/marchproxy.MediaService/GetStream',
                request_serializer=marchproxy_dot_media__pb2.GetStreamRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetStreamResponse.FromString,
                _registered_method=True)
        self.StopStream = channel.unary_unary(
                '/marchproxy.MediaService/StopStream',
                request_serializer=marchproxy_dot_media__pb2.StopStreamRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.StopStreamResponse.FromString,
                _registered_method=True)
        self.GetStreamStats = channel.unary_unary(
                '/marchproxy.MediaService/GetStreamStats',
                request_serializer=marchproxy_dot_media__pb2.GetStreamStatsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetStreamStatsResponse.FromString,
                _registered_method=True)
        self.GetBitrateProfiles = channel.unary_unary(
                '/marchproxy.MediaService/GetBitrateProfiles',
                request_serializer=marchproxy_dot_media__pb2.GetBitrateProfilesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetBitrateProfilesResponse.FromString,
                _registered_method=True)
        self.SetBitrateProfiles = channel.unary_unary(
                '/marchproxy.MediaService/SetBitrateProfiles',
                request_serializer=marchproxy_dot_media__pb2.SetBitrateProfilesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.SetBitrateProfilesResponse.FromString,
                _registered_method=True)
        self.AddRestreamDestination = channel.unary_unary(
                '/marchproxy.MediaService/AddRestreamDestination',
                request_serializer=marchproxy_dot_media__pb2.AddRestreamDestinationRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.AddRestreamDestinationResponse.FromString,
                _registered_method=True)
        self.RemoveRestreamDestination = channel.unary_unary(
                '/marchproxy.MediaService/RemoveRestreamDestination',
                request_serializer=marchproxy_dot_media__pb2.RemoveRestreamDestinationRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.RemoveRestreamDestinationResponse.FromString,
                _registered_method=True)
        self.ListRestreamDestinations = channel.unary_unary(
                '/marchproxy.MediaService/ListRestreamDestinations',
                request_serializer=marchproxy_dot_media__pb2.ListRestreamDestinationsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.ListRestreamDestinationsResponse.FromString,
                _registered_method=True)
        self.StartRestream = channel.unary_unary(
                '/marchproxy.MediaService/StartRestream',
                request_serializer=marchproxy_dot_media__pb2.StartRestreamRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.StartRestreamResponse.FromString,
                _registered_method=True)
        self.StopRestream = channel.unary_unary(
                '/marchproxy.MediaService/StopRestream',
                request_serializer=marchproxy_dot_media__pb2.StopRestreamRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.StopRestreamResponse.FromString,
                _registered_method=True)
        self.GetMediaStats = channel.unary_unary(
                '/marchproxy.MediaService/GetMediaStats',
                request_serializer=marchproxy_dot_media__pb2.GetMediaStatsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.GetMediaStatsResponse.FromString,
                _registered_method=True)
        self.StreamMediaStats = channel.unary_stream(
                '/marchproxy.MediaService/StreamMediaStats',
                request_serializer=marchproxy_dot_media__pb2.StreamMediaStatsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_media__pb2.StreamMediaStatsResponse.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """MediaService provides RTMP/Media module specific operations.
    This extends the base ModuleService with media-specific functionality.
    Hardware and Capability Management
    """

    def GetCapabilities(self, request, context):
        """GetCapabilities returns the hardware capabilities of this media instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffectiveLimits(self, request, context):
        """GetEffectiveLimits returns the effective resolution/bitrate limits
        considering both hardware capabilities and admin policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Policy Management (from Manager/Admin)

        UpdatePolicy updates the media policy from the Manager service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """GetPolicy returns the current media policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStreams(self, request, context):
        """Stream Management

        ListStreams returns all active streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """GetStream returns details of a specific stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """StopStream terminates a specific stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamStats(self, request, context):
        """GetStreamStats returns statistics for a specific stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBitrateProfiles(self, request, context):
        """Transcode Ladder Management

        GetBitrateProfiles returns configured bitrate profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBitrateProfiles(self, request, context):
        """SetBitrateProfiles configures the transcode ladder
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRestreamDestination(self, request, context):
        """Restreaming

        AddRestreamDestination adds a restream destination (Twitch, YouTube, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRestreamDestination(self, request, context):
        """RemoveRestreamDestination removes a restream destination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRestreamDestinations(self, request, context):
        """ListRestreamDestinations lists all configured restream destinations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRestream(self, request, context):
        """StartRestream starts restreaming to a destination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRestream(self, request, context):
        """StopRestream stops restreaming to a destination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMediaStats(self, request, context):
        """Media Statistics

        GetMediaStats returns media-specific statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMediaStats(self, request, context):
        """StreamMediaStats streams real-time media statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=marchproxy_dot_media__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'GetEffectiveLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffectiveLimits,
                    request_deserializer=marchproxy_dot_media__pb2.GetEffectiveLimitsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetEffectiveLimitsResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=marchproxy_dot_media__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=marchproxy_dot_media__pb2.GetPolicyRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetPolicyResponse.SerializeToString,
            ),
            'ListStreams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStreams,
                    request_deserializer=marchproxy_dot_media__pb2.ListStreamsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.ListStreamsResponse.SerializeToString,
            ),
            'GetStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=marchproxy_dot_media__pb2.GetStreamRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetStreamResponse.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=marchproxy_dot_media__pb2.StopStreamRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.StopStreamResponse.SerializeToString,
            ),
            'GetStreamStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamStats,
                    request_deserializer=marchproxy_dot_media__pb2.GetStreamStatsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetStreamStatsResponse.SerializeToString,
            ),
            'GetBitrateProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBitrateProfiles,
                    request_deserializer=marchproxy_dot_media__pb2.GetBitrateProfilesRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetBitrateProfilesResponse.SerializeToString,
            ),
            'SetBitrateProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBitrateProfiles,
                    request_deserializer=marchproxy_dot_media__pb2.SetBitrateProfilesRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.SetBitrateProfilesResponse.SerializeToString,
            ),
            'AddRestreamDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRestreamDestination,
                    request_deserializer=marchproxy_dot_media__pb2.AddRestreamDestinationRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.AddRestreamDestinationResponse.SerializeToString,
            ),
            'RemoveRestreamDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRestreamDestination,
                    request_deserializer=marchproxy_dot_media__pb2.RemoveRestreamDestinationRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.RemoveRestreamDestinationResponse.SerializeToString,
            ),
            'ListRestreamDestinations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRestreamDestinations,
                    request_deserializer=marchproxy_dot_media__pb2.ListRestreamDestinationsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.ListRestreamDestinationsResponse.SerializeToString,
            ),
            'StartRestream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRestream,
                    request_deserializer=marchproxy_dot_media__pb2.StartRestreamRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.StartRestreamResponse.SerializeToString,
            ),
            'StopRestream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRestream,
                    request_deserializer=marchproxy_dot_media__pb2.StopRestreamRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.StopRestreamResponse.SerializeToString,
            ),
            'GetMediaStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMediaStats,
                    request_deserializer=marchproxy_dot_media__pb2.GetMediaStatsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.GetMediaStatsResponse.SerializeToString,
            ),
            'StreamMediaStats': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMediaStats,
                    request_deserializer=marchproxy_dot_media__pb2.StreamMediaStatsRequest.FromString,
                    response_serializer=marchproxy_dot_media__pb2.StreamMediaStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marchproxy.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marchproxy.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """MediaService provides RTMP/Media module specific operations.
    This extends the base ModuleService with media-specific functionality.
    Hardware and Capability Management
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetCapabilities',
            marchproxy_dot_media__pb2.GetCapabilitiesRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffectiveLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetEffectiveLimits',
            marchproxy_dot_media__pb2.GetEffectiveLimitsRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetEffectiveLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/UpdatePolicy',
            marchproxy_dot_media__pb2.UpdatePolicyRequest.SerializeToString,
            marchproxy_dot_media__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetPolicy',
            marchproxy_dot_media__pb2.GetPolicyRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStreams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/ListStreams',
            marchproxy_dot_media__pb2.ListStreamsRequest.SerializeToString,
            marchproxy_dot_media__pb2.ListStreamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetStream',
            marchproxy_dot_media__pb2.GetStreamRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/StopStream',
            marchproxy_dot_media__pb2.StopStreamRequest.SerializeToString,
            marchproxy_dot_media__pb2.StopStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetStreamStats',
            marchproxy_dot_media__pb2.GetStreamStatsRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetStreamStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBitrateProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetBitrateProfiles',
            marchproxy_dot_media__pb2.GetBitrateProfilesRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetBitrateProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBitrateProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/SetBitrateProfiles',
            marchproxy_dot_media__pb2.SetBitrateProfilesRequest.SerializeToString,
            marchproxy_dot_media__pb2.SetBitrateProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRestreamDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/AddRestreamDestination',
            marchproxy_dot_media__pb2.AddRestreamDestinationRequest.SerializeToString,
            marchproxy_dot_media__pb2.AddRestreamDestinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRestreamDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/RemoveRestreamDestination',
            marchproxy_dot_media__pb2.RemoveRestreamDestinationRequest.SerializeToString,
            marchproxy_dot_media__pb2.RemoveRestreamDestinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRestreamDestinations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/ListRestreamDestinations',
            marchproxy_dot_media__pb2.ListRestreamDestinationsRequest.SerializeToString,
            marchproxy_dot_media__pb2.ListRestreamDestinationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRestream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/StartRestream',
            marchproxy_dot_media__pb2.StartRestreamRequest.SerializeToString,
            marchproxy_dot_media__pb2.StartRestreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRestream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/StopRestream',
            marchproxy_dot_media__pb2.StopRestreamRequest.SerializeToString,
            marchproxy_dot_media__pb2.StopRestreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMediaStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.MediaService/GetMediaStats',
            marchproxy_dot_media__pb2.GetMediaStatsRequest.SerializeToString,
            marchproxy_dot_media__pb2.GetMediaStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMediaStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marchproxy.MediaService/StreamMediaStats',
            marchproxy_dot_media__pb2.StreamMediaStatsRequest.SerializeToString,
            marchproxy_dot_media__pb2.StreamMediaStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
