# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import module_pb2 as marchproxy_dot_module__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marchproxy/module_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleServiceStub(object):
    """ModuleService is the interface that all module containers (ALB, DBLB, AILB, RTMP) must implement.
    This allows the NLB to uniformly manage and communicate with all modules.
    Lifecycle Management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/marchproxy.ModuleService/GetStatus',
                request_serializer=marchproxy_dot_module__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/marchproxy.ModuleService/Reload',
                request_serializer=marchproxy_dot_module__pb2.ReloadRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/marchproxy.ModuleService/Shutdown',
                request_serializer=marchproxy_dot_module__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.CanHandle = channel.unary_unary(
                '/marchproxy.ModuleService/CanHandle',
                request_serializer=marchproxy_dot_module__pb2.CanHandleRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.CanHandleResponse.FromString,
                _registered_method=True)
        self.GetRoutes = channel.unary_unary(
                '/marchproxy.ModuleService/GetRoutes',
                request_serializer=marchproxy_dot_module__pb2.GetRoutesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetRoutesResponse.FromString,
                _registered_method=True)
        self.UpdateRoutes = channel.unary_unary(
                '/marchproxy.ModuleService/UpdateRoutes',
                request_serializer=marchproxy_dot_module__pb2.UpdateRoutesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.UpdateRoutesResponse.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/marchproxy.ModuleService/DeleteRoute',
                request_serializer=marchproxy_dot_module__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.DeleteRouteResponse.FromString,
                _registered_method=True)
        self.GetRateLimits = channel.unary_unary(
                '/marchproxy.ModuleService/GetRateLimits',
                request_serializer=marchproxy_dot_module__pb2.GetRateLimitsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetRateLimitsResponse.FromString,
                _registered_method=True)
        self.SetRateLimit = channel.unary_unary(
                '/marchproxy.ModuleService/SetRateLimit',
                request_serializer=marchproxy_dot_module__pb2.SetRateLimitRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.SetRateLimitResponse.FromString,
                _registered_method=True)
        self.RemoveRateLimit = channel.unary_unary(
                '/marchproxy.ModuleService/RemoveRateLimit',
                request_serializer=marchproxy_dot_module__pb2.RemoveRateLimitRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.RemoveRateLimitResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/marchproxy.ModuleService/GetMetrics',
                request_serializer=marchproxy_dot_module__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.Scale = channel.unary_unary(
                '/marchproxy.ModuleService/Scale',
                request_serializer=marchproxy_dot_module__pb2.ScaleRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.ScaleResponse.FromString,
                _registered_method=True)
        self.GetInstances = channel.unary_unary(
                '/marchproxy.ModuleService/GetInstances',
                request_serializer=marchproxy_dot_module__pb2.GetInstancesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetInstancesResponse.FromString,
                _registered_method=True)
        self.SetTrafficWeight = channel.unary_unary(
                '/marchproxy.ModuleService/SetTrafficWeight',
                request_serializer=marchproxy_dot_module__pb2.SetTrafficWeightRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.SetTrafficWeightResponse.FromString,
                _registered_method=True)
        self.GetActiveVersion = channel.unary_unary(
                '/marchproxy.ModuleService/GetActiveVersion',
                request_serializer=marchproxy_dot_module__pb2.GetActiveVersionRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetActiveVersionResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/marchproxy.ModuleService/Rollback',
                request_serializer=marchproxy_dot_module__pb2.RollbackRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.PromoteVersion = channel.unary_unary(
                '/marchproxy.ModuleService/PromoteVersion',
                request_serializer=marchproxy_dot_module__pb2.PromoteVersionRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.PromoteVersionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marchproxy.ModuleService/HealthCheck',
                request_serializer=marchproxy_dot_module__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/marchproxy.ModuleService/GetStats',
                request_serializer=marchproxy_dot_module__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/marchproxy.ModuleService/StreamMetrics',
                request_serializer=marchproxy_dot_module__pb2.StreamMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.StreamMetricsResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/marchproxy.ModuleService/GetConfig',
                request_serializer=marchproxy_dot_module__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/marchproxy.ModuleService/UpdateConfig',
                request_serializer=marchproxy_dot_module__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=marchproxy_dot_module__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)


class ModuleServiceServicer(object):
    """ModuleService is the interface that all module containers (ALB, DBLB, AILB, RTMP) must implement.
    This allows the NLB to uniformly manage and communicate with all modules.
    Lifecycle Management
    """

    def GetStatus(self, request, context):
        """GetStatus returns the current status of the module instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Reload reloads the module configuration without restarting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown gracefully shuts down the module instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CanHandle(self, request, context):
        """Traffic Routing

        CanHandle checks if this module can handle the given route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutes(self, request, context):
        """GetRoutes returns all routes this module is configured to handle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoutes(self, request, context):
        """UpdateRoutes updates the routing configuration for this module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """DeleteRoute removes a specific route from this module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRateLimits(self, request, context):
        """Rate Limiting

        GetRateLimits returns current rate limiting configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRateLimit(self, request, context):
        """SetRateLimit configures a rate limit for a target
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRateLimit(self, request, context):
        """RemoveRateLimit removes a rate limit configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Scaling and Instance Management

        GetMetrics returns current metrics for this module instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scale(self, request, context):
        """Scale adjusts the scaling configuration for this module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstances(self, request, context):
        """GetInstances returns information about all instances of this module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrafficWeight(self, request, context):
        """Blue/Green Deployment

        SetTrafficWeight sets the traffic weight for this instance (blue/green)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveVersion(self, request, context):
        """GetActiveVersion returns the currently active version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Rollback rolls back to the previous version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteVersion(self, request, context):
        """PromoteVersion promotes a version from canary to full production
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health and Monitoring

        HealthCheck performs a health check on this module instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """GetStats returns detailed statistics for this module instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """StreamMetrics streams real-time metrics (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Configuration Management

        GetConfig returns the current configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """UpdateConfig updates the module configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=marchproxy_dot_module__pb2.GetStatusRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetStatusResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=marchproxy_dot_module__pb2.ReloadRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.ReloadResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=marchproxy_dot_module__pb2.ShutdownRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.ShutdownResponse.SerializeToString,
            ),
            'CanHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.CanHandle,
                    request_deserializer=marchproxy_dot_module__pb2.CanHandleRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.CanHandleResponse.SerializeToString,
            ),
            'GetRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutes,
                    request_deserializer=marchproxy_dot_module__pb2.GetRoutesRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetRoutesResponse.SerializeToString,
            ),
            'UpdateRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoutes,
                    request_deserializer=marchproxy_dot_module__pb2.UpdateRoutesRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.UpdateRoutesResponse.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=marchproxy_dot_module__pb2.DeleteRouteRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.DeleteRouteResponse.SerializeToString,
            ),
            'GetRateLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRateLimits,
                    request_deserializer=marchproxy_dot_module__pb2.GetRateLimitsRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetRateLimitsResponse.SerializeToString,
            ),
            'SetRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRateLimit,
                    request_deserializer=marchproxy_dot_module__pb2.SetRateLimitRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.SetRateLimitResponse.SerializeToString,
            ),
            'RemoveRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRateLimit,
                    request_deserializer=marchproxy_dot_module__pb2.RemoveRateLimitRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.RemoveRateLimitResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=marchproxy_dot_module__pb2.GetMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetMetricsResponse.SerializeToString,
            ),
            'Scale': grpc.unary_unary_rpc_method_handler(
                    servicer.Scale,
                    request_deserializer=marchproxy_dot_module__pb2.ScaleRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.ScaleResponse.SerializeToString,
            ),
            'GetInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstances,
                    request_deserializer=marchproxy_dot_module__pb2.GetInstancesRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetInstancesResponse.SerializeToString,
            ),
            'SetTrafficWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrafficWeight,
                    request_deserializer=marchproxy_dot_module__pb2.SetTrafficWeightRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.SetTrafficWeightResponse.SerializeToString,
            ),
            'GetActiveVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveVersion,
                    request_deserializer=marchproxy_dot_module__pb2.GetActiveVersionRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetActiveVersionResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=marchproxy_dot_module__pb2.RollbackRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.RollbackResponse.SerializeToString,
            ),
            'PromoteVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteVersion,
                    request_deserializer=marchproxy_dot_module__pb2.PromoteVersionRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.PromoteVersionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=marchproxy_dot_module__pb2.HealthCheckRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=marchproxy_dot_module__pb2.GetStatsRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetStatsResponse.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=marchproxy_dot_module__pb2.StreamMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.StreamMetricsResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=marchproxy_dot_module__pb2.GetConfigRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.GetConfigResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=marchproxy_dot_module__pb2.UpdateConfigRequest.FromString,
                    response_serializer=marchproxy_dot_module__pb2.UpdateConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marchproxy.ModuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marchproxy.ModuleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleService(object):
    """ModuleService is the interface that all module containers (ALB, DBLB, AILB, RTMP) must implement.
    This allows the NLB to uniformly manage and communicate with all modules.
    Lifecycle Management
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetStatus',
            marchproxy_dot_module__pb2.GetStatusRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/Reload',
            marchproxy_dot_module__pb2.ReloadRequest.SerializeToString,
            marchproxy_dot_module__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/Shutdown',
            marchproxy_dot_module__pb2.ShutdownRequest.SerializeToString,
            marchproxy_dot_module__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CanHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/CanHandle',
            marchproxy_dot_module__pb2.CanHandleRequest.SerializeToString,
            marchproxy_dot_module__pb2.CanHandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetRoutes',
            marchproxy_dot_module__pb2.GetRoutesRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/UpdateRoutes',
            marchproxy_dot_module__pb2.UpdateRoutesRequest.SerializeToString,
            marchproxy_dot_module__pb2.UpdateRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/DeleteRoute',
            marchproxy_dot_module__pb2.DeleteRouteRequest.SerializeToString,
            marchproxy_dot_module__pb2.DeleteRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRateLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetRateLimits',
            marchproxy_dot_module__pb2.GetRateLimitsRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetRateLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/SetRateLimit',
            marchproxy_dot_module__pb2.SetRateLimitRequest.SerializeToString,
            marchproxy_dot_module__pb2.SetRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/RemoveRateLimit',
            marchproxy_dot_module__pb2.RemoveRateLimitRequest.SerializeToString,
            marchproxy_dot_module__pb2.RemoveRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetMetrics',
            marchproxy_dot_module__pb2.GetMetricsRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/Scale',
            marchproxy_dot_module__pb2.ScaleRequest.SerializeToString,
            marchproxy_dot_module__pb2.ScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetInstances',
            marchproxy_dot_module__pb2.GetInstancesRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrafficWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/SetTrafficWeight',
            marchproxy_dot_module__pb2.SetTrafficWeightRequest.SerializeToString,
            marchproxy_dot_module__pb2.SetTrafficWeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetActiveVersion',
            marchproxy_dot_module__pb2.GetActiveVersionRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetActiveVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/Rollback',
            marchproxy_dot_module__pb2.RollbackRequest.SerializeToString,
            marchproxy_dot_module__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/PromoteVersion',
            marchproxy_dot_module__pb2.PromoteVersionRequest.SerializeToString,
            marchproxy_dot_module__pb2.PromoteVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/HealthCheck',
            marchproxy_dot_module__pb2.HealthCheckRequest.SerializeToString,
            marchproxy_dot_module__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetStats',
            marchproxy_dot_module__pb2.GetStatsRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marchproxy.ModuleService/StreamMetrics',
            marchproxy_dot_module__pb2.StreamMetricsRequest.SerializeToString,
            marchproxy_dot_module__pb2.StreamMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/GetConfig',
            marchproxy_dot_module__pb2.GetConfigRequest.SerializeToString,
            marchproxy_dot_module__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.ModuleService/UpdateConfig',
            marchproxy_dot_module__pb2.UpdateConfigRequest.SerializeToString,
            marchproxy_dot_module__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
