# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import waddleai_pb2 as marchproxy_dot_waddleai__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marchproxy/waddleai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WaddleAIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRoute = channel.unary_unary(
                '/marchproxy.WaddleAIService/EvaluateRoute',
                request_serializer=marchproxy_dot_waddleai__pb2.RouteRequest.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.EvaluateSecurity = channel.unary_unary(
                '/marchproxy.WaddleAIService/EvaluateSecurity',
                request_serializer=marchproxy_dot_waddleai__pb2.SecurityRequest.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.SecurityResponse.FromString,
                _registered_method=True)
        self.StoreTurn = channel.unary_unary(
                '/marchproxy.WaddleAIService/StoreTurn',
                request_serializer=marchproxy_dot_waddleai__pb2.StoreTurnRequest.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.StoreTurnResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/marchproxy.WaddleAIService/GetContext',
                request_serializer=marchproxy_dot_waddleai__pb2.GetContextRequest.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.SearchMemories = channel.unary_unary(
                '/marchproxy.WaddleAIService/SearchMemories',
                request_serializer=marchproxy_dot_waddleai__pb2.SearchMemoriesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.SearchMemoriesResponse.FromString,
                _registered_method=True)
        self.ReportUsage = channel.unary_unary(
                '/marchproxy.WaddleAIService/ReportUsage',
                request_serializer=marchproxy_dot_waddleai__pb2.UsageReport.SerializeToString,
                response_deserializer=marchproxy_dot_waddleai__pb2.UsageAck.FromString,
                _registered_method=True)


class WaddleAIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateRoute(self, request, context):
        """Routing: Evaluate prompt complexity, return model recommendation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateSecurity(self, request, context):
        """Security: Evaluate raw tool command for threats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTurn(self, request, context):
        """Memory: Store conversation turn
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Memory: Retrieve context for session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemories(self, request, context):
        """Memory: Search memories
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUsage(self, request, context):
        """Usage: Report token usage per model/user (Premium — license-gated on WaddleAI side)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaddleAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRoute,
                    request_deserializer=marchproxy_dot_waddleai__pb2.RouteRequest.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.RouteResponse.SerializeToString,
            ),
            'EvaluateSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSecurity,
                    request_deserializer=marchproxy_dot_waddleai__pb2.SecurityRequest.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.SecurityResponse.SerializeToString,
            ),
            'StoreTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTurn,
                    request_deserializer=marchproxy_dot_waddleai__pb2.StoreTurnRequest.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.StoreTurnResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=marchproxy_dot_waddleai__pb2.GetContextRequest.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.GetContextResponse.SerializeToString,
            ),
            'SearchMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemories,
                    request_deserializer=marchproxy_dot_waddleai__pb2.SearchMemoriesRequest.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.SearchMemoriesResponse.SerializeToString,
            ),
            'ReportUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUsage,
                    request_deserializer=marchproxy_dot_waddleai__pb2.UsageReport.FromString,
                    response_serializer=marchproxy_dot_waddleai__pb2.UsageAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marchproxy.WaddleAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marchproxy.WaddleAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaddleAIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/EvaluateRoute',
            marchproxy_dot_waddleai__pb2.RouteRequest.SerializeToString,
            marchproxy_dot_waddleai__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/EvaluateSecurity',
            marchproxy_dot_waddleai__pb2.SecurityRequest.SerializeToString,
            marchproxy_dot_waddleai__pb2.SecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/StoreTurn',
            marchproxy_dot_waddleai__pb2.StoreTurnRequest.SerializeToString,
            marchproxy_dot_waddleai__pb2.StoreTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/GetContext',
            marchproxy_dot_waddleai__pb2.GetContextRequest.SerializeToString,
            marchproxy_dot_waddleai__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/SearchMemories',
            marchproxy_dot_waddleai__pb2.SearchMemoriesRequest.SerializeToString,
            marchproxy_dot_waddleai__pb2.SearchMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.WaddleAIService/ReportUsage',
            marchproxy_dot_waddleai__pb2.UsageReport.SerializeToString,
            marchproxy_dot_waddleai__pb2.UsageAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
