"""Generated gRPC code for PenguinCode client-server communication."""

from .penguincode_pb2 import (  # Auth messages; Chat messages; Health messages; Tool messages
    AgentResult,
    AgentSpawn,
    AuthRequest,
    AuthResponse,
    ChatRequest,
    ChatResponse,
    ClientCapabilities,
    CloseSessionRequest,
    CloseSessionResponse,
    CreateSessionRequest,
    CreateSessionResponse,
    Error,
    GetHistoryRequest,
    GetHistoryResponse,
    HealthCheckRequest,
    HealthCheckResponse,
    HistoryMessage,
    RefreshRequest,
    ServerInfo,
    StatusUpdate,
    TextChunk,
    ToolRequest,
    ToolResponse,
    ValidateRequest,
    ValidateResponse,
)
from .penguincode_pb2_grpc import (  # Service servicers (server-side); Service stubs (client-side); Server registration functions
    AuthServiceServicer,
    AuthServiceStub,
    ChatServiceServicer,
    ChatServiceStub,
    HealthServiceServicer,
    HealthServiceStub,
    ToolCallbackServiceServicer,
    ToolCallbackServiceStub,
    add_AuthServiceServicer_to_server,
    add_ChatServiceServicer_to_server,
    add_HealthServiceServicer_to_server,
    add_ToolCallbackServiceServicer_to_server,
)

__all__ = [
    # Auth
    "AuthRequest",
    "AuthResponse",
    "RefreshRequest",
    "ValidateRequest",
    "ValidateResponse",
    # Chat
    "CreateSessionRequest",
    "CreateSessionResponse",
    "ClientCapabilities",
    "ServerInfo",
    "ChatRequest",
    "ChatResponse",
    "TextChunk",
    "AgentSpawn",
    "AgentResult",
    "StatusUpdate",
    "Error",
    "GetHistoryRequest",
    "GetHistoryResponse",
    "HistoryMessage",
    "CloseSessionRequest",
    "CloseSessionResponse",
    # Tools
    "ToolRequest",
    "ToolResponse",
    # Health
    "HealthCheckRequest",
    "HealthCheckResponse",
    # Stubs
    "AuthServiceStub",
    "ChatServiceStub",
    "ToolCallbackServiceStub",
    "HealthServiceStub",
    # Servicers
    "AuthServiceServicer",
    "ChatServiceServicer",
    "ToolCallbackServiceServicer",
    "HealthServiceServicer",
    # Registration
    "add_AuthServiceServicer_to_server",
    "add_ChatServiceServicer_to_server",
    "add_ToolCallbackServiceServicer_to_server",
    "add_HealthServiceServicer_to_server",
]
