# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import nlb_pb2 as marchproxy_dot_nlb__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marchproxy/nlb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLBServiceStub(object):
    """NLBService is the service that the NLB container provides for module registration,
    routing updates, and metrics reporting.
    Module Registration and Discovery
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModule = channel.unary_unary(
                '/marchproxy.NLBService/RegisterModule',
                request_serializer=marchproxy_dot_nlb__pb2.RegisterModuleRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.RegisterModuleResponse.FromString,
                _registered_method=True)
        self.UnregisterModule = channel.unary_unary(
                '/marchproxy.NLBService/UnregisterModule',
                request_serializer=marchproxy_dot_nlb__pb2.UnregisterModuleRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.UnregisterModuleResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/marchproxy.NLBService/Heartbeat',
                request_serializer=marchproxy_dot_nlb__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ListModules = channel.unary_unary(
                '/marchproxy.NLBService/ListModules',
                request_serializer=marchproxy_dot_nlb__pb2.ListModulesRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.ListModulesResponse.FromString,
                _registered_method=True)
        self.GetModuleInfo = channel.unary_unary(
                '/marchproxy.NLBService/GetModuleInfo',
                request_serializer=marchproxy_dot_nlb__pb2.GetModuleInfoRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetModuleInfoResponse.FromString,
                _registered_method=True)
        self.UpdateRouting = channel.unary_unary(
                '/marchproxy.NLBService/UpdateRouting',
                request_serializer=marchproxy_dot_nlb__pb2.UpdateRoutingRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.UpdateRoutingResponse.FromString,
                _registered_method=True)
        self.GetRoutingTable = channel.unary_unary(
                '/marchproxy.NLBService/GetRoutingTable',
                request_serializer=marchproxy_dot_nlb__pb2.GetRoutingTableRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetRoutingTableResponse.FromString,
                _registered_method=True)
        self.RouteRequest = channel.unary_unary(
                '/marchproxy.NLBService/RouteRequest',
                request_serializer=marchproxy_dot_nlb__pb2.RouteRequestRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.RouteRequestResponse.FromString,
                _registered_method=True)
        self.ValidateRoute = channel.unary_unary(
                '/marchproxy.NLBService/ValidateRoute',
                request_serializer=marchproxy_dot_nlb__pb2.ValidateRouteRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.ValidateRouteResponse.FromString,
                _registered_method=True)
        self.ReportMetrics = channel.unary_unary(
                '/marchproxy.NLBService/ReportMetrics',
                request_serializer=marchproxy_dot_nlb__pb2.ReportMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.ReportMetricsResponse.FromString,
                _registered_method=True)
        self.GetNLBMetrics = channel.unary_unary(
                '/marchproxy.NLBService/GetNLBMetrics',
                request_serializer=marchproxy_dot_nlb__pb2.GetNLBMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetNLBMetricsResponse.FromString,
                _registered_method=True)
        self.GetModuleMetrics = channel.unary_unary(
                '/marchproxy.NLBService/GetModuleMetrics',
                request_serializer=marchproxy_dot_nlb__pb2.GetModuleMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetModuleMetricsResponse.FromString,
                _registered_method=True)
        self.StreamNLBMetrics = channel.unary_stream(
                '/marchproxy.NLBService/StreamNLBMetrics',
                request_serializer=marchproxy_dot_nlb__pb2.StreamNLBMetricsRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.StreamNLBMetricsResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/marchproxy.NLBService/CheckHealth',
                request_serializer=marchproxy_dot_nlb__pb2.CheckHealthRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.CheckHealthResponse.FromString,
                _registered_method=True)
        self.GetNLBStatus = channel.unary_unary(
                '/marchproxy.NLBService/GetNLBStatus',
                request_serializer=marchproxy_dot_nlb__pb2.GetNLBStatusRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetNLBStatusResponse.FromString,
                _registered_method=True)
        self.UpdateNLBConfig = channel.unary_unary(
                '/marchproxy.NLBService/UpdateNLBConfig',
                request_serializer=marchproxy_dot_nlb__pb2.UpdateNLBConfigRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.UpdateNLBConfigResponse.FromString,
                _registered_method=True)
        self.GetNLBConfig = channel.unary_unary(
                '/marchproxy.NLBService/GetNLBConfig',
                request_serializer=marchproxy_dot_nlb__pb2.GetNLBConfigRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetNLBConfigResponse.FromString,
                _registered_method=True)
        self.RebalanceLoad = channel.unary_unary(
                '/marchproxy.NLBService/RebalanceLoad',
                request_serializer=marchproxy_dot_nlb__pb2.RebalanceLoadRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.RebalanceLoadResponse.FromString,
                _registered_method=True)
        self.GetLoadDistribution = channel.unary_unary(
                '/marchproxy.NLBService/GetLoadDistribution',
                request_serializer=marchproxy_dot_nlb__pb2.GetLoadDistributionRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.GetLoadDistributionResponse.FromString,
                _registered_method=True)
        self.TriggerScaling = channel.unary_unary(
                '/marchproxy.NLBService/TriggerScaling',
                request_serializer=marchproxy_dot_nlb__pb2.TriggerScalingRequest.SerializeToString,
                response_deserializer=marchproxy_dot_nlb__pb2.TriggerScalingResponse.FromString,
                _registered_method=True)


class NLBServiceServicer(object):
    """NLBService is the service that the NLB container provides for module registration,
    routing updates, and metrics reporting.
    Module Registration and Discovery
    """

    def RegisterModule(self, request, context):
        """RegisterModule registers a new module instance with the NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterModule(self, request, context):
        """UnregisterModule removes a module instance from the NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat sends periodic heartbeat from module to NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModules(self, request, context):
        """ListModules returns all registered modules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleInfo(self, request, context):
        """GetModuleInfo returns detailed information about a specific module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRouting(self, request, context):
        """Routing Management

        UpdateRouting updates the routing configuration for the NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingTable(self, request, context):
        """GetRoutingTable returns the current routing table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteRequest(self, request, context):
        """RouteRequest routes a single request to the appropriate module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateRoute(self, request, context):
        """ValidateRoute validates if a route can be handled
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """Metrics and Monitoring

        ReportMetrics allows modules to report metrics to the NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNLBMetrics(self, request, context):
        """GetNLBMetrics returns aggregated NLB metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleMetrics(self, request, context):
        """GetModuleMetrics returns metrics for a specific module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNLBMetrics(self, request, context):
        """StreamNLBMetrics streams real-time NLB metrics (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Health and Status

        CheckHealth performs health check on the NLB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNLBStatus(self, request, context):
        """GetNLBStatus returns current NLB status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNLBConfig(self, request, context):
        """Configuration Management

        UpdateNLBConfig updates the NLB configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNLBConfig(self, request, context):
        """GetNLBConfig returns the current NLB configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebalanceLoad(self, request, context):
        """Load Balancing and Scaling

        RebalanceLoad triggers load rebalancing across modules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoadDistribution(self, request, context):
        """GetLoadDistribution returns current load distribution across modules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerScaling(self, request, context):
        """TriggerScaling triggers scaling operations for a module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModule': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModule,
                    request_deserializer=marchproxy_dot_nlb__pb2.RegisterModuleRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.RegisterModuleResponse.SerializeToString,
            ),
            'UnregisterModule': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterModule,
                    request_deserializer=marchproxy_dot_nlb__pb2.UnregisterModuleRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.UnregisterModuleResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=marchproxy_dot_nlb__pb2.HeartbeatRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ListModules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModules,
                    request_deserializer=marchproxy_dot_nlb__pb2.ListModulesRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.ListModulesResponse.SerializeToString,
            ),
            'GetModuleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleInfo,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetModuleInfoRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetModuleInfoResponse.SerializeToString,
            ),
            'UpdateRouting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRouting,
                    request_deserializer=marchproxy_dot_nlb__pb2.UpdateRoutingRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.UpdateRoutingResponse.SerializeToString,
            ),
            'GetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingTable,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetRoutingTableRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetRoutingTableResponse.SerializeToString,
            ),
            'RouteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteRequest,
                    request_deserializer=marchproxy_dot_nlb__pb2.RouteRequestRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.RouteRequestResponse.SerializeToString,
            ),
            'ValidateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRoute,
                    request_deserializer=marchproxy_dot_nlb__pb2.ValidateRouteRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.ValidateRouteResponse.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=marchproxy_dot_nlb__pb2.ReportMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.ReportMetricsResponse.SerializeToString,
            ),
            'GetNLBMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNLBMetrics,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetNLBMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetNLBMetricsResponse.SerializeToString,
            ),
            'GetModuleMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleMetrics,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetModuleMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetModuleMetricsResponse.SerializeToString,
            ),
            'StreamNLBMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNLBMetrics,
                    request_deserializer=marchproxy_dot_nlb__pb2.StreamNLBMetricsRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.StreamNLBMetricsResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=marchproxy_dot_nlb__pb2.CheckHealthRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.CheckHealthResponse.SerializeToString,
            ),
            'GetNLBStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNLBStatus,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetNLBStatusRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetNLBStatusResponse.SerializeToString,
            ),
            'UpdateNLBConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNLBConfig,
                    request_deserializer=marchproxy_dot_nlb__pb2.UpdateNLBConfigRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.UpdateNLBConfigResponse.SerializeToString,
            ),
            'GetNLBConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNLBConfig,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetNLBConfigRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetNLBConfigResponse.SerializeToString,
            ),
            'RebalanceLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.RebalanceLoad,
                    request_deserializer=marchproxy_dot_nlb__pb2.RebalanceLoadRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.RebalanceLoadResponse.SerializeToString,
            ),
            'GetLoadDistribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoadDistribution,
                    request_deserializer=marchproxy_dot_nlb__pb2.GetLoadDistributionRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.GetLoadDistributionResponse.SerializeToString,
            ),
            'TriggerScaling': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerScaling,
                    request_deserializer=marchproxy_dot_nlb__pb2.TriggerScalingRequest.FromString,
                    response_serializer=marchproxy_dot_nlb__pb2.TriggerScalingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marchproxy.NLBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marchproxy.NLBService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLBService(object):
    """NLBService is the service that the NLB container provides for module registration,
    routing updates, and metrics reporting.
    Module Registration and Discovery
    """

    @staticmethod
    def RegisterModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/RegisterModule',
            marchproxy_dot_nlb__pb2.RegisterModuleRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.RegisterModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/UnregisterModule',
            marchproxy_dot_nlb__pb2.UnregisterModuleRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.UnregisterModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/Heartbeat',
            marchproxy_dot_nlb__pb2.HeartbeatRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/ListModules',
            marchproxy_dot_nlb__pb2.ListModulesRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.ListModulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModuleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetModuleInfo',
            marchproxy_dot_nlb__pb2.GetModuleInfoRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetModuleInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/UpdateRouting',
            marchproxy_dot_nlb__pb2.UpdateRoutingRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.UpdateRoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetRoutingTable',
            marchproxy_dot_nlb__pb2.GetRoutingTableRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetRoutingTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/RouteRequest',
            marchproxy_dot_nlb__pb2.RouteRequestRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.RouteRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/ValidateRoute',
            marchproxy_dot_nlb__pb2.ValidateRouteRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.ValidateRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/ReportMetrics',
            marchproxy_dot_nlb__pb2.ReportMetricsRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.ReportMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNLBMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetNLBMetrics',
            marchproxy_dot_nlb__pb2.GetNLBMetricsRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetNLBMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModuleMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetModuleMetrics',
            marchproxy_dot_nlb__pb2.GetModuleMetricsRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetModuleMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNLBMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marchproxy.NLBService/StreamNLBMetrics',
            marchproxy_dot_nlb__pb2.StreamNLBMetricsRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.StreamNLBMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/CheckHealth',
            marchproxy_dot_nlb__pb2.CheckHealthRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.CheckHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNLBStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetNLBStatus',
            marchproxy_dot_nlb__pb2.GetNLBStatusRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetNLBStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNLBConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/UpdateNLBConfig',
            marchproxy_dot_nlb__pb2.UpdateNLBConfigRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.UpdateNLBConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNLBConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetNLBConfig',
            marchproxy_dot_nlb__pb2.GetNLBConfigRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetNLBConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebalanceLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/RebalanceLoad',
            marchproxy_dot_nlb__pb2.RebalanceLoadRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.RebalanceLoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoadDistribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/GetLoadDistribution',
            marchproxy_dot_nlb__pb2.GetLoadDistributionRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.GetLoadDistributionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerScaling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marchproxy.NLBService/TriggerScaling',
            marchproxy_dot_nlb__pb2.TriggerScalingRequest.SerializeToString,
            marchproxy_dot_nlb__pb2.TriggerScalingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
