# Cloudflare Pages configuration for WaddleAI website
# This file configures deployment settings for waddlebot.ai

# Build settings
build:
  # Build command to run
  command: "npm run build"
  
  # Build output directory (Next.js static export)
  output_directory: "out"
  
  # Root directory for build
  root_dir: "."

# Environment variables for build
environment:
  NODE_VERSION: "18.x"
  NPM_VERSION: "latest"

# Custom headers for security and caching
headers:
  # Security headers
  - source: "/*"
    headers:
      - key: "X-Frame-Options"
        value: "DENY"
      - key: "X-Content-Type-Options"
        value: "nosniff"
      - key: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"
      - key: "Permissions-Policy"
        value: "camera=(), microphone=(), geolocation=()"
  
  # Cache static assets
  - source: "/_next/static/*"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000, immutable"

# Redirects
redirects:
  # Redirect old domain if needed
  # - source: "https://old-domain.com/*"
  #   destination: "https://waddlebot.ai/:splat"
  #   status: 301