name = "waddleai-website"
compatibility_date = "2024-01-01"

[env.production]
name = "waddleai-website-production"

[build]
command = "npm run build"
cwd = "."

[[pages_build_output_dir]]
value = "out"