name = "waddleai-docs"
compatibility_date = "2024-01-01"

[env.production]
name = "waddleai-docs-production"

pages_build_output_dir = "site"

[build]
command = "pip install -r requirements.txt && cd docs-site && mkdocs build && mv site ../site"
cwd = "."