# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import proxy_pb2 as waddleai_dot_v1_dot_proxy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in waddleai/v1/proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WaddleAIServiceStub(object):
    """Health checking uses the standard grpc.health.v1.Health service
    (grpcio-health-checking), wired at server startup — not redefined here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRoute = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/EvaluateRoute',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.RouteRequest.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.EvaluateSecurity = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/EvaluateSecurity',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.SecurityRequest.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.SecurityResponse.FromString,
                _registered_method=True)
        self.StoreTurn = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/StoreTurn',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.StoreTurnRequest.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.StoreTurnResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/GetContext',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.GetContextRequest.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.SearchMemories = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/SearchMemories',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesRequest.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesResponse.FromString,
                _registered_method=True)
        self.ReportUsage = channel.unary_unary(
                '/waddleai.v1.WaddleAIService/ReportUsage',
                request_serializer=waddleai_dot_v1_dot_proxy__pb2.UsageReport.SerializeToString,
                response_deserializer=waddleai_dot_v1_dot_proxy__pb2.UsageAck.FromString,
                _registered_method=True)


class WaddleAIServiceServicer(object):
    """Health checking uses the standard grpc.health.v1.Health service
    (grpcio-health-checking), wired at server startup — not redefined here.
    """

    def EvaluateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateSecurity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaddleAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRoute,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.RouteRequest.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.RouteResponse.SerializeToString,
            ),
            'EvaluateSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSecurity,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.SecurityRequest.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.SecurityResponse.SerializeToString,
            ),
            'StoreTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTurn,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.StoreTurnRequest.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.StoreTurnResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.GetContextRequest.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.GetContextResponse.SerializeToString,
            ),
            'SearchMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemories,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesRequest.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesResponse.SerializeToString,
            ),
            'ReportUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUsage,
                    request_deserializer=waddleai_dot_v1_dot_proxy__pb2.UsageReport.FromString,
                    response_serializer=waddleai_dot_v1_dot_proxy__pb2.UsageAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waddleai.v1.WaddleAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('waddleai.v1.WaddleAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaddleAIService(object):
    """Health checking uses the standard grpc.health.v1.Health service
    (grpcio-health-checking), wired at server startup — not redefined here.
    """

    @staticmethod
    def EvaluateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/EvaluateRoute',
            waddleai_dot_v1_dot_proxy__pb2.RouteRequest.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/EvaluateSecurity',
            waddleai_dot_v1_dot_proxy__pb2.SecurityRequest.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.SecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/StoreTurn',
            waddleai_dot_v1_dot_proxy__pb2.StoreTurnRequest.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.StoreTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/GetContext',
            waddleai_dot_v1_dot_proxy__pb2.GetContextRequest.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/SearchMemories',
            waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesRequest.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.SearchMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddleai.v1.WaddleAIService/ReportUsage',
            waddleai_dot_v1_dot_proxy__pb2.UsageReport.SerializeToString,
            waddleai_dot_v1_dot_proxy__pb2.UsageAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
